### ISSUE TITLE
Ansible-lint crash when using action with module parameters

### ISSUE THREAD

**Issue by Yannig** [willthames/ansible-lint#106]
Here's a simple example showing this crash:
```yaml
---
- name: "Crash ansible-lint"
  gather_facts: no
  hosts: "localhost"
  tasks:
    - anything: module=test
```

Launching **ansible-lint test.yml** result in following crash:

```
Traceback (most recent call last):
  File "./bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/yannig/dev/yannig/ansible-lint/lib/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/yannig/dev/yannig/ansible-lint/lib/ansiblelint/__init__.py", line 123, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/yannig/dev/yannig/ansible-lint/lib/ansiblelint/__init__.py", line 59, in matchtasks
    for task in ansiblelint.utils.get_action_tasks(yaml, file):
  File "/home/yannig/dev/yannig/ansible-lint/lib/ansiblelint/utils.py", line 292, in get_action_tasks
    if 'include' not in task.keys()]
  File "/home/yannig/dev/yannig/ansible-lint/lib/ansiblelint/utils.py", line 240, in normalize_task
    v = _kv_to_dict(k + ' ' + v)
  File "/home/yannig/dev/yannig/ansible-lint/lib/ansiblelint/utils.py", line 222, in _kv_to_dict
    return (dict(module=command, module_arguments=args, **kwargs))
TypeError: type object got multiple values for keyword argument 'module'
```

I'll send you a PR which rename module keys into __ansible_module__ and fix this crash.

**Comment by Yannig** [comment]
I can confirm, using last version from git that this bug is now gone :)

Thanks !
