### ISSUE TITLE
Misreading of include containing playbook_dir

### ISSUE THREAD

**Issue by siddharthist** [willthames/ansible-lint#113]
I just got the following traceback which can be reproduced as follows:
```
$ git clone https://github.com/CiscoCloud/mantl
$ find . -name "*.yml" -exec ansible-lint {} \; -exec echo "PLAYBOOK: " {} \;                                                                                 
Traceback (most recent call last):
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 115, in run
    with open(playbookfile['path'], 'Ur') as f:
IOError: [Errno 2] No such file or directory: u'/home/siddharthist/Dropbox/code/asteris/mantl/addons/playbooks/check-requirements.yml'
Traceback (most recent call last):
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/siddharthist/.virtualenvs/mantl/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 211, in run
    skip_list=set(self.skip_list)))
  File "/home/siddharthist/.virtualenvs/mantl/lib/python2.7/site-packages/ansiblelint/__init__.py", line 115, in run
    with open(playbookfile['path'], 'Ur') as f:
IOError: [Errno 2] No such file or directory: u'/home/siddharthist/Dropbox/code/asteris/mantl/addons/playbooks/check-requirements.yml'
PLAYBOOK  ./addons/iptables.yml
```
Looks like there's a problem with parsing [the include line in that playbook](https://github.com/CiscoCloud/mantl/blob/da44f77a50ba1908b8e84eb190e78a3ffb496824/addons/elk.yml#L7).

**Comment by willthames** [comment]
It's definitely a bug as we should never throw a stack trace.

However, at the moment, ansible-lint does no templating of playbooks/roles at all - so dynamic includes don't really work (this is because ansible-lint doesn't really know what variables will expand to at runtime - we could special case playbook_dir but that might be a lot of work for one use case)

I should be able to remove the stack trace easily enough if that is acceptable.

**Comment by siddharthist** [comment]
That would be great! In my opinion, ansible-lint should simply ignore include lines with variables, (or do that for anything except `playbook_dir`, which is unambiguous).

**Comment by willthames** [comment]
Hmm, this gets stranger. Looking again at the file being opened, `playbook_dir` must be being expanded, but incorrectly. I'll need to dig into this further once I have some time.

**Comment by siddharthist** [comment]
@willthames Have you been able to make any progress on this?

**Comment by willthames** [comment]
@siddharthist please test #119
