### ISSUE TITLE
Traceback: KeyError: 'role' : utils.py:176

### ISSUE THREAD

**Issue by ssbarnea** [willthames/ansible-lint#123]
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 201, in run
    for file in ansiblelint.utils.find_children(arg):
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 122, in find_children
    for child in play_children(basedir, item, playbook[1]):
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 152, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 176, in _roles_children
    results.extend(_look_for_role_files(basedir, role['role']))
KeyError: 'role'
```
And the playbook is as simple as it can be:
```
---
- hosts:
  - "{{ hosts }}"

  roles:
    - name: xxx
```

I can assure you that the xxx exists and is loaded by ansible. 

Still, it seems that ansible-lint does fail to load the role path from the `ansible.cfg` but this would be a new bug, first this must become a proper error, not an traceback.

**Comment by willthames** [comment]
@ssbarnea please use the issue template that I provided for this project.

One of the fundamental requirements is a minimal complete verifiable example.

If you can't submit issues that meet the requirements, I will close all of your issues.

**Comment by ssbarnea** [comment]
I guess this would be the fundamentable one, assuming you do not have an existing xxx role.
```
---
- hosts:localhost
  roles:
    - name: xxx
```

**Comment by willthames** [comment]
Well that example is irrelevant to this issue. So it's not a verifiable example.

The issue with your example above is that roles are expected to be a list of things that are either a role name or a dictionary containing a `role` key (this is basic, documented stuff - http://docs.ansible.com/ansible/playbooks_roles.html#roles)

Unfortunately ansible-lint is designed to be run on things that ansible-playbook will treat as a valid playbook. This is not one of those things. 

If you change `name: xxx` to `role: xxx` it works fine.

I'm going to close this, in future, please use the issue template.

**Comment by ssbarnea** [comment]
Sure. Is there a way to disable the traceback errors? They give a really bad user experience and they prevent creating a proper integration with a GUI linter. 

Syntax errors are to be expected, and the linter is supposed to identify them, but not with a huge tracedump like the one below:
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 201, in run
    for file in ansiblelint.utils.find_children(arg):
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 119, in find_children
    pb_data = parse_yaml_from_file(playbook[0])
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 42, in parse_yaml_from_file
    return dl.load_from_file(filepath)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 114, in load_from_file
    parsed_data = self.load(data=file_data, file_name=file_name, show_content=show_content)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 95, in load
    self._handle_error(yaml_exc, file_name, show_content)
  File "/usr/local/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 191, in _handle_error
    raise AnsibleParserError(YAML_SYNTAX_ERROR, obj=err_obj, show_content=show_content)
ansible.errors.AnsibleParserError: Syntax Error while loading YAML.


The error appears to have been in '/Users/sorins/bmll/devops/tests/test.yml': line 2, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- hosts:localhost
  roles:
       ^ here
```

Another proof that this is a real bug is the fact that even calling with `-p` flag it would give the same kind of output instead of pep8 output format.

**Comment by willthames** [comment]
Yep, if you can test #126 to see if it meets your needs, please do - if it looks good, I'll merge it in.
