### ISSUE TITLE
Allow templating of playbook_dir failure

### ISSUE THREAD

**Issue by pabelanger** [willthames/ansible-lint#130]
So, it looks like there is a path problem with https://github.com/willthames/ansible-lint/pull/119.  To reproduce:

$ git clone https://github.com/openstack/ansible-role-jenkins
$ cd ansible-role-jenkins
$ tox -elinters

linters create: /home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters
linters installdeps: -r/home/pabelanger/git/openstack/ansible-role-jenkins/requirements.txt, -r/home/pabelanger/git/openstack/ansible-role-jenkins/test-requirements.txt
linters installed: You are using pip version 7.1.2, however version 8.1.1 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,ansible==2.0.1.0,ansible-lint==2.4.1,docutils==0.12,ecdsa==0.13,flake8==2.2.4,hacking==0.10.2,Jinja2==2.8,MarkupSafe==0.23,mccabe==0.2.1,paramiko==1.16.0,pbr==1.8.1,pep8==1.5.7,pycrypto==2.6.1,pyflakes==0.8.1,Pygments==2.1.3,PyYAML==3.11,six==1.10.0,Sphinx==1.2.3,wheel==0.24.0
linters runtests: PYTHONHASHSEED='2365006016'
linters runtests: commands[0] | flake8
linters runtests: commands[1] | bash -c find . -type f -regex '.*.y[a]?ml' -print0 | xargs -t -n1 -0 ansible-lint
ansible-lint ./tasks/config.yaml 
ansible-lint ./tasks/service.yaml 
ansible-lint ./tasks/install.yaml 
ansible-lint ./tasks/main.yaml 
ansible-lint ./handlers/main.yaml 
ansible-lint ./defaults/main.yaml 
ansible-lint ./meta/main.yml 
ansible-lint ./vars/RedHat.yaml 
ansible-lint ./vars/Debian.yaml 
ansible-lint ./tests/test.yaml 
Traceback (most recent call last):
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/bin/ansible-lint", line 116, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/bin/ansible-lint", line 103, in main
    matches = runner.run()
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansiblelint/__init__.py", line 201, in run
    for file in ansiblelint.utils.find_children(arg):
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansiblelint/utils.py", line 122, in find_children
    for child in play_children(basedir, item, playbook[1]):
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansiblelint/utils.py", line 151, in play_children
    v = template(basedir, v, dict(playbook_dir=os.path.abspath(basedir)), fail_on_undefined=False)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansiblelint/utils.py", line 53, in template
    return templar.template(varname, **kwargs)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/template/__init__.py", line 349, in template
    return [self.template(v, preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides) for v in variable]
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/template/__init__.py", line 356, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/template/__init__.py", line 356, in template
    d[k] = self.template(variable[k], preserve_trailing_newlines=preserve_trailing_newlines, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/template/__init__.py", line 328, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/template/__init__.py", line 489, in _do_template
    res = j2_concat(rf)
  File "<template>", line 8, in root
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/jinja2/runtime.py", line 196, in call
    return __obj(*args, **kwargs)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/template/__init__.py", line 410, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/plugins/lookup/file.py", line 51, in run
    contents, show_data = self._loader._get_file_contents(lookupfile)
  File "/home/pabelanger/git/openstack/ansible-role-jenkins/.tox/linters/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 161, in _get_file_contents
    raise AnsibleFileNotFound("the file_name '%s' does not exist, or is not readable" % file_name)
ansible.errors.AnsibleFileNotFound: the file_name './tests/files/jenkins/jenkins-ci.org.key' does not exist, or is not readable
ERROR: InvocationError: "/usr/bin/bash -c find . -type f -regex '.*.y[a]?ml' -print0 | xargs -t -n1 -0 ansible-lint"
_______________________________________________ summary ________________________________________________
ERROR:   linters: commands failed

**Comment by willthames** [comment]
Fixed by #130, thanks!
