### ISSUE TITLE
Type error with pre-commit on mac at initialisation

### ISSUE THREAD

**Issue by JonLev** [willthames/ansible-lint#276]
# Issue Type
- Bug report

# Ansible and Ansible Lint details
On macOS, python 3.5.3
```
ansible --version: not installed
ansible-lint --version 3.4.13
```

- ansible installation method: None
- ansible-lint installation method: pre-commit

# Desired Behaviour
Work at initialisation
# Actual Behaviour (Bug report only)

### Pre-commit config
```
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/willthames/ansible-lint.git
    sha: v3.4.13
    hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
```

It may be related to [Issue #204 ](https://github.com/willthames/ansible-lint/issues/204). I'm looking to virtualenv version of pyenv. I will edit the issue if needed

### What happened
```
~/repo ᐅ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/willthames/ansible-lint.git.
[INFO] Installing environment for https://github.com/willthames/ansible-lint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Trim Trailing Whitespace.................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Check for added large files..............................................Passed
Ansible-lint.............................................................Failed
hookid: ansible-lint

Traceback (most recent call last):
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/bin/ansible-lint", line 11, in <module>
    load_entry_point('ansible-lint==3.4.13', 'console_scripts', 'ansible-lint')()
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/main/__init__.py", line 122, in main
    matches.extend(runner.run())
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/__init__.py", line 229, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/utils.py", line 158, in find_children
    for child in play_children(basedir, item, playbook[1], playbook_dir):
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/utils.py", line 207, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/utils.py", line 253, in _roles_children
    role.get('role', role.get('name'))))
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/utils.py", line 301, in _look_for_role_files
    role_path = _rolepath(basedir, role)
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/site-packages/ansiblelint/utils.py", line 272, in _rolepath
    path_dwim(basedir, os.path.join('roles', role)),
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/admin/.pre-commit/repoi3jdki9d/py_env-default/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'

~/repo ᐅ ansible-lint ./**
Traceback (most recent call last):
  File "/Users/admin/.pyenv/versions/destygo_env/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/main/__init__.py", line 122, in main
    matches.extend(runner.run())
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/__init__.py", line 229, in run
    for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/utils.py", line 158, in find_children
    for child in play_children(basedir, item, playbook[1], playbook_dir):
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/utils.py", line 207, in play_children
    return delegate_map[k](basedir, k, v, parent_type)
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/utils.py", line 253, in _roles_children
    role.get('role', role.get('name'))))
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/utils.py", line 301, in _look_for_role_files
    role_path = _rolepath(basedir, role)
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/site-packages/ansiblelint/utils.py", line 272, in _rolepath
    path_dwim(basedir, os.path.join('roles', role)),
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/admin/.pyenv/versions/3.5.3/envs/destygo_env/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'

**Comment by JonLev** [comment]
Just checked: it's not related to virtualenv as [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv#virtualenv-and-venv) use venv, the successor of virtualenv that is included by default in python now

**Comment by JonLev** [comment]
I tried the playbook live, and it seems some base syntax errors were there (`var` instead of `vars` for instance). The hook worked after fixed these errors. Not a big issue then, but it was ansible that report the specific error and the linter just failed. It should be the linter first I suppose.

Closing the issue.
