### ISSUE TITLE
Is installation possible in windows?

### ISSUE THREAD

**Issue by jonmelia** [willthames/ansible-lint#328]
Not sure if it is possible to install in Windows, but would like confirmation if it isn't

# Issue Type
- Bug report
Unable to install via Python and Pip in Windows..

Error message:
c:\Python27amd64\Scripts>pip install ansible-lint
Collecting ansible-lint
  Using cached ansible-lint-3.4.20.tar.gz
Collecting ansible (from ansible-lint)
  Using cached ansible-2.4.3.0.tar.gz
Exception:
Traceback (most recent call last):
  File "c:\python27amd64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27amd64\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python27amd64\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27amd64\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python27amd64\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\python27amd64\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\python27amd64\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "c:\python27amd64\lib\site-packages\pip\utils\__init__.py", line 553, in untar_file
    ensure_dir(path)
  File "c:\python27amd64\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\python27amd64\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 206] The filename or extension is too long: 'c:\\users\\user\\appdata\\local\\temp\\pip-build-sz048m\\ansible\\test/integration/targets/copy/files/subdir/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/circles/subdir1/'

# Ansible and Ansible Lint details

```
ansible --version
ansible-lint --version
```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

# Desired Behaviour

Please give some details of the feature being requested
or what should happen if providing a bug report

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve)
with:
- playbook
- output of running ansible-lint
- if you're getting a stack trace, output of
  `ansible-playbook --syntax-check playbook`

**Comment by willthames** [comment]
From your bug report, I'm going to say it's not currently possible, but if someone can come up with a fix for the installation bug I'll try and merge that fix.

I have no idea what's going on with your install - looks like we might have a circular symlink in the test directory (likely the file named `circles`, for good reason) and Windows is *not* coping with that well! There might be a better way to write that test that allows ansible-lint to install on windows.

**Comment by jonmelia** [comment]
Thanks for the quick response.  Would be great if someone with the required knowledge around the installation could do some further investigation..

**Comment by jonmelia** [comment]
See also https://github.com/ansible/ansible/issues/31419

**Comment by cvick** [comment]
I've have it installed on Windows 7 using Python 2.7.14. I notice in your error message you used `pip`, I used `pip2` to install on mine. It looks like you're using Python 2 so I would see if that works. But, that may be because I have both Python 2 and 3 installed.

Also, I had to install a few other things before I was able to properly install ansible-lint. If you use [Cygwin](https://www.cygwin.com/), try installing:

- `gcc`
- `make`
- `python2-devel`
- `python2-wheel`

**Comment by KingJ** [comment]
I was able to install ansible-lint on Windows 10 through pip (Python 3.5), but I don't think it's going to work natively. For example, I get a `ModuleNotFoundError: No module named 'grp'` error sourced from ansible itself when I try and run ansible-lint. In Python on Windows, the grp module does not exist. 

At the moment, i'm toying with using the Windows Subsystem for Linux so that I can trigger ansible-lint from Windows, it runs in WSL and returns back to Windows. If that works, i'll open a PR with some documentation for how to do that!

**Comment by jborean93** [comment]
Just add a few things to this convo, the error regarding the long path in the 31419 is now resolved (I believe 2.5+ is fine now), we also have added a linter to file/path names as part of the sanity check to hopefully pick up any of these issues happening in the future.

This just means Ansible can be installed with pip but running it is another story and will produce weird results like @KingJ mentioned.

**Comment by awcrosby** [comment]
As with ansible, we don't support installing ansible-lint directly on a windows machine

**Comment by RHCEv3** [comment]
In general the issue is this *HAS* to work in WINDOWS.  I HATE that excuse for an "os" but that is what I am given by the government agency I work for and that's all there is - PEROID.   And there is no ssh to a Linux anything as the Linux systems are on a totally different network you can ONLY get to via VDI so it's code, Push to git, go to environment then to Linux server, pull from Git and run.

And having been in UIT 26+ years that is the NORM and NOT uncommon at all.   I think we'd ALL be FAR better off and a LOT more secure with a Linux secure desktop but that's just not going to happen so 

THIS   HAS   TO   WORK   IN   WINDOWS 10 !!!   As long as no admin rights are needed (as I have none) and can install to user home then I'll help test ANYTHING as I have been waiting 4-5 years for this.

**Comment by RHCEv3** [comment]
> As with ansible, we don't support installing ansible-lint directly on a windows machine

So you are ENDORSING TERRAFORM and HASHICORP VAULT then????    Because that is the net effect of NOTHING foe windows the last 5 years.
