### ISSUE TITLE
ansible-lint chockes when it finds inline import role

### ISSUE THREAD

**Issue by ssbarnea** [willthames/ansible-lint#349]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible-lint 3.4.23
```

# Desired Behaviour

Linting error or no error at all, but clearly not an exception.

# Actual Behaviour (Bug report only)

```
Traceback (most recent call last):
File "/Users/ssbarnea/.pyenv/versions/2.7.14/bin/ansible-lint", line 11, in <module>
sys.exit(main())
File "/Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansiblelint/__main__.py", line 176, in main
matches.extend(runner.run())
File "/Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansiblelint/__init__.py", line 229, in run
for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
File "/Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansiblelint/utils.py", line 171, in find_children
for child in play_children(basedir, item, playbook[1], playbook_dir):
File "/Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansiblelint/utils.py", line 221, in play_children
return delegate_map[k](basedir, k, v, parent_type)
File "/Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansiblelint/utils.py", line 247, in _taskshandlers_children
results.extend(_roles_children(basedir, k, [th['import_role'].get('name')], parent_type,
AttributeError: 'AnsibleUnicode' object has no attribute 'get'
```

How to reproduce:

See https://review.gerrithub.io/c/redhat-openstack/infrared/+/415772/2/plugins/tripleo-overcloud/build_templates.yml

**Comment by XenGi** [comment]
This even fails when the role name is on a seperate line like this:

```
- include_role:
      name: "myrole"

```

**Comment by willthames** [comment]
Is this still a problem with latest ansible-lint? I thought I'd merged and published the fix for this

**Comment by cnorthwood** [comment]
I still get this error with 3.5.1

**Comment by charisz** [comment]
Mee too 3.5.1

**Comment by cnorthwood** [comment]
I can confirm this still happens with 4.1.0

**Comment by dazzla76** [comment]
Is there any update on this or any potential workarounds?

**Comment by awcrosby** [comment]
Thanks for bumping this up, we will get a fix for this into the next bugfix release
