### ISSUE TITLE
AssertionError on roles: in playbook

### ISSUE THREAD

**Issue by mikebell** [willthames/ansible-lint#66]
Running ansible-lint 2.0.3

I get AssertionError on the following playbook:

```
---
- hosts: all
  sudo: yes
  vars_files:
    - "./vars/main.yml"
    - "./vars/sites.yml"
  tasks:
    - name: register rvm
      stat: path=/home/vagrant/.rvm
      register: rvmpath
    - name: install python-pycurl
      apt: pkg=python-pycurl state=latest
    - name: Create ssh config file
      template: src=../files/config dest=/home/vagrant/.ssh/config owner=vagrant group=vagrant mode=0644
    - name: Create Databases
      mysql_db: name={{ item }} state=present login_user="root" login_password={{ mariadb_root_password }}
      with_items: mysql_dbs.keys()
      tags: db
    - name: Create DB Users
      mysql_user: name={{ item.value.user }} password={{ item.value.pass }} priv="{{ item.key }}.*:ALL" login_user="root" login_password={{ mariadb_root_password }}
      tags: db
      with_dict: mysql_dbs
  roles:
    - common
    - { role: ansible-mariadb55 }
    - { role: jdauphant.nginx, tags: nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.drush }
    - { role: geerlingguy.java }
    - { role: geerlingguy.solr }
    - { role: geerlingguy.php-xdebug, php_xdebug_max_nesting_level: 256}
    - { role: geerlingguy.mailhog }
  handlers:
    - name: update repositories
      apt: update_cache=yes cache_valid_time=3600
```

Error:
```
mbell@Michaels-MacBook-Pro-2 [10:42:08] [~/Vagrant/drupaldev-vm] [dev *]
-> % ansible-lint provisioning/playbook.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 104, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 91, in main
    matches = runner.run()
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 179, in run
    skip_tags=set(self.skip_tags)))
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 113, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/Library/Python/2.7/site-packages/ansiblelint/__init__.py", line 60, in matchtasks
    for task in utils.get_action_tasks(yaml, file):
  File "/Library/Python/2.7/site-packages/ansiblelint/utils.py", line 219, in get_action_tasks
    if 'include' not in task.keys()]
  File "/Library/Python/2.7/site-packages/ansiblelint/utils.py", line 192, in normalize_task
    assert False
AssertionError
```
Removing the roles block doesn't cause this issue.

**Comment by willthames** [comment]
Ok, this problem doesn't seem to occur with the current codebase. However, pypi didn't reflect the current codebase.

I've updated pypi so that if you're using pip, you can just update to the latest (2.1.0). 

If you're still having a problem, please raise a new issue.
