### ISSUE TITLE
Compatilbility with Ansible 2.x

### ISSUE THREAD

**Issue by BobBoldin** [willthames/ansible-lint#75]
While on ansible 1.9x working fine.   Clean install of Ansible 2.x (devel branch) and having issue of module parse_yaml_from_file not available.

ansible-lint playbooks/test_update.yml 
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 4, in <module>
    __import__('pkg_resources').run_script('ansible-lint==2.1.3', 'ansible-lint')
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/ansible_lint-2.1.3-py2.6.egg/EGG-INFO/scripts/ansible-lint", line 110, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/ansible_lint-2.1.3-py2.6.egg/EGG-INFO/scripts/ansible-lint", line 97, in main
    matches = runner.run()
  File "/usr/lib/python2.6/site-packages/ansible_lint-2.1.3-py2.6.egg/ansiblelint/__init__.py", line 172, in run
    for file in ansiblelint.utils.find_children(arg):
  File "/usr/lib/python2.6/site-packages/ansible_lint-2.1.3-py2.6.egg/ansiblelint/utils.py", line 87, in find_children
    pb_data = ansible.utils.parse_yaml_from_file(playbook[0])
AttributeError: 'module' object has no attribute 'parse_yaml_from_file'

**Comment by willthames** [comment]
@BobBoldin yeah, that doesn't surprise me at all. I have as yet made no effort to support Ansible 2.0 as it's been a moving target for months. I think it's settling down now though, but I don't have much time to devote to resolving these issues. 

I suspect it'll need a similar approach - a v2.0 branch with a proper release once Ansible 2.0 is released.

**Comment by pstauffer** [comment]
Hi Will,

first of all, thanks for your effort with the ansible-lint tool!

If you're planing to support Ansible 2.0 in the future, it would be nice to add rules with the new best practices. Like a rule for the sudo/su "replacement" with "become" (invented in version 1.9  - http://docs.ansible.com/ansible/become.html).

I know, Ansible 2.0 should be backward-compatible, but I could help you to create a list with recommendations for the new version.

Greets
Pascal

**Comment by dmsimard** [comment]
Heya, just following up on this .. Ansible 2 release candidate is out, maybe we can start looking at compatibility ? https://github.com/ansible/ansible/releases/tag/v2.0.0-0.6.rc1

**Comment by willthames** [comment]
@pstauffer, I would support new rules for such deprecation warnings.

**Comment by willthames** [comment]
ansible-lint 2.3.0 is compatible with Ansible 2.0
