### ISSUE TITLE
Trackback error - not sure if ansible-lint or atom-lint

### ISSUE THREAD

**Issue by NeckBeardPrince** [willthames/ansible-lint#93]
Error: Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 113, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/ansible-lint", line 100, in main
    matches = runner.run()
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 208, in run
    skip_list=set(self.skip_list)))
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 120, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/__init__.py", line 59, in matchtasks
    for task in ansiblelint.utils.get_action_tasks(yaml, file):
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 283, in get_action_tasks
    tasks.extend(extract_from_list(yaml, ['tasks', 'handlers', 'pre_tasks', 'post_tasks']))
  File "/usr/local/lib/python2.7/site-packages/ansiblelint/utils.py", line 275, in extract_from_list
    results.extend(block[candidate])
TypeError: 'NoneType' object is not iterable
    at parameters.exit (/Users/adam/.atom/packages/linter-ansible-linting/node_modules/atom-linter/lib/helpers.js:58:20)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by willthames** [comment]
A traceback really isn't enough information to fix this bug. If you are unable to fix the code yourself, please provide a minimal verifiable complete example that triggers the behaviour:

http://stackoverflow.com/help/mcve

**Comment by phemmer** [comment]
I'm also seeing this issue. It seems the error is caused when you have a `tasks`, `pre_tasks`, `post_tasks`, or `handlers` which is empty

To reproduce, create a playbook with the following:

    - tasks:

...and run the linter against it.

**Comment by achaussier** [comment]
Hello,

The PR https://github.com/willthames/ansible-lint/pull/108 will return an explicit message instead of the traceback

**Comment by ssbarnea** [comment]
Any reason for not closing this? The PR was merged?
